imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    # .. existing import here
    - { resource: "@WarBlogBundle/Resources/config/config.yml"}
    - { resource: doctrine_extensions.yml }
#    - { resource: "@BlogBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
#        types:
#            json: Sonata\Doctrine\Types\JsonType
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
#        naming_strategy: doctrine.orm.entity_managers.default
        auto_mapping: true
        mappings:
            translatable:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Translatable\Entity
                # make sure vendor library location is correct
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity/MappedSuperclass" 
#        entity_managers:
#            default:
#                mappings:
#                    ApplicationSonataMediaBundle: ~                    
#                    SonataMediaBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
assetic:
#    debug: '%kernel.debug%'
#    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
#        yui_css:
#            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
            #apply_to: '\.css$'
        uglifyjs2:
           bin: "%kernel.root_dir%/Resources/node_modules/uglify-js/bin/uglifycss" 
        uglifycss:
           bin: %kernel.root_dir%/Resources/node_modules/uglifycss/uglifycss
# SonataAdminBundle
sonata_admin:
    title: WarBlog Admin
    title_logo: images/kozak1.png
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.admin.block.search_result:
            contexts: [admin]
        sonata.block.service.text: 
        sonata.block.service.action: 
        sonata.block.service.rss: 
#sonata_media:
    # if you don't use default namespace configuration
    #class:
    #    media:        MyVendor\MediaBundle\Entity\Media
    #    gallery:      MyVendor\MediaBundle\Entity\Gallery
    #    gallery_item: MyVendor\MediaBundle\Entity\GalleryItem
#    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr it is mandatory to choose one here
#    default_context: default # you need to set a context
#    contexts:
#        default:  # the default context is mandatory
#            providers:
#                - sonata.media.provider.dailymotion
#                - sonata.media.provider.youtube
#                - sonata.media.provider.image
#                - sonata.media.provider.file
#                - sonata.media.provider.vimeo
#            formats:
#                small: { width: 100 , quality: 70}
#                big:   { width: 500 , quality: 70}
#    cdn:
#        server:
#            path: /uploads/media # http://media.sonata-project.org/
#    filesystem:
#        local:
#            directory:  "%kernel.root_dir%/../web/uploads/media"
#            create:     false
#    providers:
#        image:
#            resizer: sonata.media.resizer.square            
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: War\BlogBundle\Entity\User
    group:
        group_class: War\BlogBundle\Entity\Group
